// carlito | DiPlay property client; vehicle implementation is in a separate GD bridge APK.
plugins { id("com.android.library") }

dependencies { implementation(libs.androidx.core.ktx) }

android {
    namespace = "com.shilapi.xcertplay.vehicleprobe"
    compileSdk = 37
    // carlito | Use the Java contract generated by GD; Windows aidl cannot write to UNC paths.
    // The matching .aidl remains the protocol source alongside this client.
    buildFeatures { aidl = false }
    defaultConfig {
        // carlito | The client follows DiPlay; the separately installed GD bridge still needs Android 9.
        minSdk = 25
        consumerProguardFiles("consumer-rules.pro")
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}
